"""update users table

Revision ID: a49645f37f55
Revises: 6659db96ad9d
Create Date: 2025-05-14 12:18:19.462190

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a49645f37f55"
down_revision: Union[str, None] = "6659db96ad9d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("profiles", "first_name", existing_type=sa.VARCHAR(length=40), nullable=True)
    op.alter_column("profiles", "last_name", existing_type=sa.VARCHAR(length=40), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("profiles", "last_name", existing_type=sa.VARCHAR(length=40), nullable=False)
    op.alter_column("profiles", "first_name", existing_type=sa.VARCHAR(length=40), nullable=False)
    # ### end Alembic commands ###
