"""add_count_to_ass_tbl

Revision ID: 4c985119c5be
Revises: a056db92d5aa
Create Date: 2025-06-23 07:41:34.223536

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4c985119c5be"
down_revision: Union[str, None] = "a056db92d5aa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("order_product_association", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("quantity", sa.Integer(), server_default="1", nullable=False)
        )
        batch_op.drop_constraint("id_unique_order_product", type_="unique")
        batch_op.create_unique_constraint("idx_unique_order_product", ["order_id", "product_id"])
        batch_op.drop_column("count")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("order_product_association", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("count", sa.INTEGER(), server_default=sa.text("'1'"), nullable=False)
        )
        batch_op.drop_constraint("idx_unique_order_product", type_="unique")
        batch_op.create_unique_constraint("id_unique_order_product", ["order_id", "product_id"])
        batch_op.drop_column("quantity")

    # ### end Alembic commands ###
